CHAOS_STACK_ID=b03cbd74dfd934b8

SNS_TOPIC=chaos-csv-notification-topic-$CHAOS_STACK_ID
SQS_QUEUE=chaos-csv-work-queue-$CHAOS_STACK_ID
LAMBDA_FUNCTION=ChaosTransformer-$CHAOS_STACK_ID
S3_BUCKET=chaos-bucket-$CHAOS_STACK_ID

export SNS_TOPIC SQS_QUEUE LAMBDA_FUNCTION S3_BUCKET
