CHAOS_STACK_ID=d07d378176b040d9

SNS_TOPIC=chaos-csv-notification-topic-$CHAOS_STACK_ID
LAMBDA_FUNCTION=ChaosTransformer-$CHAOS_STACK_ID
S3_BUCKET=chaos-bucket-$CHAOS_STACK_ID

export SNS_TOPIC LAMBDA_FUNCTION S3_BUCKET
